### ISSUE TITLE
Fat ray tomography

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#801] opened 2024-12-22 22:33 UTC
### Discussed in https://github.com/gimli-org/gimli/discussions/789

<div type='discussions-op-text'>

<sup>Originally posted by **makeabhishek** November 20, 2024</sup>
Hi @halbmy,
Thanks for providing the details about fat ray tomography implementation.

I was trying fat ray tomography and following #563 #564 and the references mentioned. I'm a little confuse how the weights are assigned to traveltime inversion. I understood that the weights are calculated to obtained the Fresnel volume, but it is unclear how they are used in slowness estimation. Are there detailed equations/a description of how the slowness field s is calculated using `w`? 

In traveltime tomography the traveltime is calculated using

$$t_q = \int_{L_q} \frac{1}{v(l)} dl \approx {\sum_i} {s_i} {l_i}$$

Where, $v$ is the velocity and $L_q$ the total travel path of this ray, $l_i$ are the individual ray paths in each cell, and $s_i$ are the discrete and constant slowness values. To do a forward computation, the traveltimes through each discrete cell can be determined geometrically and formulated in matrix notation as:

$$ t = G s$$

where, $t$ (i.e., first arrival traveltimes), are related to a set of model parameters $s$ (i.e., slowness),

Here, the cumulated traveltimes of all rays form the vector $t$, the slowness values of all cells are located in s and the ray paths of every ray form the matrix $G$. The matrix $G$ contains one row per ray and one column per model cell. Accordingly, measured traveltimes $t$ are associated with data vector $d$, and slowness values s are associated with the model parameters m. In summary, in the ray-approximation, the Jacobian $(G)$ consists of the ray segments per model cell. Multiplying this with the slowness vector $(s)$ produces the total traveltime of the ray along each segment. And the ray segment in each model cell actually reflects the *"sensitivity"*, as longer ray segments have a larger impact on the traveltime.

As given in Jordi et al [2016], "The main difference between the classical __ray-based__ and __fat ray__ tomography approaches is the calculation of the sensitivities. For ray tomography the sensitivities effectively are the lengths of the ray segments within the respective model cells. In the fat ray tomography scheme the sensitivities are calculated using fat rays without resorting to ray tracing." For a 2D fat ray in a discretized medium the sensitivity of the traveltime $t_i$ with respect to a change in slowness $s_k$ is given by:

$$\frac{\partial t_i}{\partial s_k} = \frac{a_{k}^{i}}{A_{i}} \cdot \frac{t_i}{s_k}$$

Is this sensitivity refer to matrix  ${l_i}$

Furthermore, in Pygimli, fatray is implemented by weighting the Jacobian or senitivity, as, 
```
pg.show(mgr.paraDomain, mgr.fop.J[7])
pg.show(mgr.paraDomain, mgr.fop.FresnelWeight[7])
```
The Jacobian (first command) contains the ray length in meters and the weight (`FresnelWeight`) is a dimensionless function summing to 1 that is being used to weight the jacobian. 

__Question__
How did the *"sensitivity"*, or  *"Jacobian"* or *"Frechet derivatives"*  incorporated in traveltime equation to obtain the slowness value? Could you refer me to the main source code?

Ref: 
1. Jordi, Claudio, Cedric Schmelzbach, and Stewart Greenhalgh. "Frequency-dependent traveltime tomography using fat rays: application to near-surface seismic imaging." Journal of Applied Geophysics 131 (2016): 202-213.
</div>

**Comment by halbmy** [comment] 2024-12-23 08:46
This is a duplicate of #789 where I just provided a comment with a link to the source code.

I consider this topic better suited as discussion and close this issue in favour of #789

**Closed by halbmy** 2024-12-23 08:46 UTC
