### ISSUE TITLE
Error: Region wise Regularization- There are cells with marker -1. Did you define a boundary region? (This is not needed).

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#530] opened 2023-05-01 21:12 UTC
### Problem description
Region wise regularization for a petrophysical inversion example. I want to fix the velocity of outer region to 2000 m/s. Attached is the image 
![geom](https://user-images.githubusercontent.com/47937684/235531722-3afe3c8c-c0a0-499f-b9ba-0c645ce3cbb2.png)
of the geometry. 

Please describe your issue here.
I have defined a geometry and want to fix  the slowness for the outer layer to perform region wise regularization. However, while performing traveltime inversion it is giving me error `Core - ERROR - There are cells with marker -1. Did you define a boundary region? (This is not needed).`

### Your environment

Please provide the output of `print(pygimli.Report())` here. If that does not
work, please give provide some additional information on your: 

OS : Linux
CPU(s) : 40
Machine : x86_64
Architecture : 64bit
RAM : 62.5 GiB
Environment : Jupyter
File system : ext4
Python 3.9.16 | packaged by conda-forge
[GCC 11.3.0]
pygimli : 1.3.1
pgcore : 1.3.0
numpy : 1.20.3
matplotlib : 3.5.1
scipy : 1.10.1
IPython : 8.11.0
pyvista : 0.34.2

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```import matplotlib.pyplot as plt
import numpy as np
import pygimli as pg
from pygimli.physics import TravelTimeManager
import pygimli.physics.traveltime as tt
import pygimli.meshtools as mt

from pygimli.meshtools import quality
import pyvista as pv
import pygimli.viewer.pv
from scipy.io import loadmat
import matplotlib as mpl 

Dout = 156 
Din = Dout -10
circle_outer = mt.createCircle(pos=[0.0, 0.0],radius=Dout/2,nSegments=64,marker=1,markerPosition=[Dout/2*0.995, 0.0])
circle_inner = mt.createCircle( pos=[0.0, 0.0], radius=Din/2, nSegments=64, marker=2, markerPosition=[Din/2*0.995, 0.0])

geom = circle_outer + circle_inner
ax, cb = pg.show(geom, markers=True)
fig = ax.get_figure()
for nr, marker in enumerate(geom.regionMarkers()):
    print('Position marker number {}:'.format(nr + 1), marker.x(), marker.y(), marker.z())
    ax.scatter(marker.x(), marker.y(), s=(2 - nr) * 30, color='k')
ax.set_title('marker positions - working example')
fig.show()

ax, _ = pg.show(geom, markers=True);
for i, n in enumerate(geom.nodes()[:12]):
    ax.text(n.x(), n.y(), str(i))
    print(i, n.x(), n.y())
    
for i in range(100, geom.nodeCount()):
    print(i, geom.node(i).x(), geom.node(i).y())

geom.addRegionMarker([0, 0], marker=2)
pg.show(geom, markers=True);

mesh = mt.createMesh(geom, quality=34.4)
for b in mesh.boundaries():
    if b.marker() == -1 and not b.outside():
        b.setMarker(2)

print(mesh)
pg.show(mesh, markers=True, showMesh=True);

pg.info("Traveltime Inversion")
mgr.inv.setRegularization(1,fix=1/2300)
velInv = mgr.invert(Testdata, mesh=mesh, lam=100, useGradient=0, zWeight=0, secNodes=2)
...
```

### Expected behavior

Aim is to have a mesh with the outer region fixed at a velocity of 2000 m/s leaving the data in between more able to reproduce a result of varying velocity.

### Actual behavior

Tell us what happens instead and/or provide the output of your script.

```
01/05/23 - 14:54:14 - pyGIMLi - INFO - Traveltime Inversion
01/05/23 - 14:54:14 - pyGIMLi - INFO - Found 2 regions.
01/05/23 - 14:54:14 - pyGIMLi - INFO - Region with smallest marker set to background (marker=1)
01/05/23 - 14:54:14 - pyGIMLi - ERROR - <class 'pygimli.physics.traveltime.TravelTimeManager.TravelTimeManager'>.checkError(TravelTimeManager.py:93)
DataContainer has no "err" values. Fallback to 3%
01/05/23 - 14:54:14 - pyGIMLi - INFO - Creating forward mesh from region infos.
01/05/23 - 14:54:14 - pyGIMLi - INFO - Creating refined mesh (secnodes: 5) to solve forward task.
01/05/23 - 14:54:14 - pyGIMLi - INFO - Create constant starting model: 0.0008039435736829754
01/05/23 - 14:54:14 - pyGIMLi - INFO - Created startmodel from forward operator: 402 [0.0008039435736829754,...,0.0008039435736829754]
01/05/23 - 14:54:14 - pyGIMLi - INFO - Starting inversion.

Reset region parameter
RegionManager copying mesh ...0.008 s 
create NeighborInfos ... 0 s 
analysing mesh ... 2 regions.
creating para domain ... 0.004 s
creating para domain ... 0.001 s
ModellingBase::setMesh() copying new mesh ... 0.004 s
FOP updating mesh dependencies ... 0 s
min/max(dweight) = 283447/554908
fop: <pygimli.physics.traveltime.modelling.TravelTimeDijkstraModelling object at 0x7f3a782a48b0>
Data transformation: <pgcore._pygimli_.RTrans object at 0x7f3a782a49f0>
Model transformation: <pgcore._pygimli_.RTransLog object at 0x7f3a782a49a0>
min/max (data): 6.0e-05/1.2e-04
min/max (error): 3%/3%
min/max (start model): 8.0e-04/8.0e-04
--------------------------------------------------------------------------------

01/05/23 - 14:54:16 - Core - ERROR - There are cells with marker -1. Did you define a boundary region? (This is not needed).

min/max(dweight) = 283447/554908
Building constraints matrix
constraint matrix of size(nBounds x nModel) 571 x 402
check Jacobian: wrong dimensions: (0x0) should be (120x402)  force: 1
jacobian size invalid, forced recalc: 1
calculating jacobian matrix (forced=1)...*** /home/carsten/miniconda3/envs/build/conda-bld/pgcore_1661190390662/work/gimli/core/src/ttdijkstramodelling.cpp:500	

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[12], line 3
      1 # Inversion
      2 pg.info("Traveltime Inversion")
----> 3 velInv = mgr.invert(data, mesh=mesh, lam=100, useGradient=0, zWeight=1.0, secNodes=5)
      5 # if want to initialise the starting model from a specific velocity
      6 #velInv = mgr.invert(data, mesh=mesh, lam=10, useGradient=0, zWeight=1.0, secNodes=2,
      7 #                 startModel=1000)
      8 
      9 #velInv = mgr.invert(secNodes=3, paraMaxCellSize=5000,zWeight=0.2, vTop=500, vBottom=6000, paraDepth=1200, verbose=1)
     10 mgr.inv.echoStatus()

File ~/anaconda3/envs/pg/lib/python3.9/site-packages/pygimli/physics/traveltime/TravelTimeManager.py:247, in TravelTimeManager.invert(self, data, useGradient, vTop, vBottom, secNodes, **kwargs)
    244 else:
    245     self.fop._useGradient = None
--> 247 slowness = super().invert(data, mesh, **kwargs)
    248 velocity = 1.0 / slowness
    249 self.fw.model = velocity

File ~/anaconda3/envs/pg/lib/python3.9/site-packages/pygimli/frameworks/methodManager.py:793, in MeshMethodManager.invert(self, data, mesh, startModel, **kwargs)
    790     self.fw.blockyModel = kwargs["blockyModel"]
    792 self.preRun(**kwargs)
--> 793 self.fw.run(dataVals, errorVals, **kwargs)
    794 self.postRun(**kwargs)
    795 return self.paraModel(self.fw.model)

File ~/anaconda3/envs/pg/lib/python3.9/site-packages/pygimli/frameworks/inversion.py:587, in Inversion.run(self, dataVals, errorVals, **kwargs)
    584 if self._preStep and callable(self._preStep):
    585     self._preStep(0, self)
--> 587 self.inv.start()
    588 self.maxIter = maxIterTmp
    590 if self._postStep and callable(self._postStep):

File ~/anaconda3/envs/pg/lib/python3.9/site-packages/pygimli/physics/traveltime/modelling.py:84, in TravelTimeDijkstraModelling.createJacobian(self, par)
     81 if not self.mesh():
     82     pg.critical("no mesh")
---> 84 return self._core.createJacobian(par)

RuntimeError: /home/carsten/miniconda3/envs/build/conda-bld/pgcore_1661190390662/work/gimli/core/src/sparsematrix.h:342		GIMLI::SparseMapMatrix<ValueType, IndexType>::MatElement GIMLI::SparseMapMatrix<ValueType, IndexType>::Aux::operator[](IndexType) [with ValueType = double; IndexType = long unsigned int; GIMLI::SparseMapMatrix<ValueType, IndexType>::MatElement = GIMLI::MatrixElement<double, long unsigned int, std::map<std::pair<long unsigned int, long unsigned int>, double, std::less<std::pair<long unsigned int, long unsigned int> >, std::allocator<std::pair<const std::pair<long unsigned int, long unsigned int>, double> > > >]  idx = 18446744073709551615, 0 maxcol = 402 stype: 0
```

> I also tried to create geometry using the data using `plc = mt.createParaMeshPLC(data, paraDepth=20, boundary=10, isClosed=true)` but not sure how to give paraDepth in circular geometry. By using paraDepth its creating a open geometry.

**Comment by halbmy** [comment] 2023-05-02 07:02
Your geometry definition with two circles looks good. However, I don't understand why you're adding another region by `geom.addRegionMarker([0, 0], marker=2)`, because the circle with cell marker 2 already defines such a region. 

At any rate, I cannot reproduce the error as I don't have the data.

**Comment by makeabhishek** [comment] 2023-05-02 16:04
[test.txt](https://github.com/gimli-org/gimli/files/11375242/test.txt)
I eliminated the `geom.addRegionMarker([0, 0], marker=2)` and used the traveltime inversion. However, having the same issue. 

```
pg.info("Traveltime Inversion")
mgr.inv.setRegularization(1,fix=1/2300)
mgr.invert(data,mesh=mesh,useGradient=False, verbose=True, isReference=True)
mgr.inv.echoStatus()
```

**Comment by makeabhishek** [comment] 2023-05-02 20:13
my bad, it was a wrong file. Here is the updated one. 
[test.txt](https://github.com/gimli-org/gimli/files/11377388/test.txt)

**Comment by makeabhishek** [comment] 2023-05-02 20:20
Apologies, mistakenly uploaded a wrong file. Here is the updated one.
[test.txt](https://github.com/gimli-org/gimli/files/11377416/test.txt)

**Comment by halbmy** [comment] 2023-05-03 06:45
The s and g fields are ok now, but the sensors are still wrong:
```
#x	 y
7.23397674	 5.53664610
2.99641128	 0.00000000
-2.99641128	 -5.53664610
-7.23397674	 -7.83000000
-7.23397674	 -5.53664610
-2.99641128	 -0.00000000
2.99641128	 5.53664610
7.23397674	 7.83000000
2.99641128	 5.53664610
7.23397674	 7.83000000
7.23397674	 5.53664610
2.99641128	 0.00000000
-2.99641128	 -5.53664610
-7.23397674	 -7.83000000
-7.23397674	 -5.53664610
-2.99641128	 -0.00000000
```
as the latter 8 sensors repeat the first ones. Please correct this first.

**Comment by makeabhishek** [comment] 2023-05-03 15:30
That's strange, It seems the data is transposed. sorry for that. Here is the new one, hope this works.
[test.txt](https://github.com/gimli-org/gimli/files/11384289/test.txt)

**Comment by halbmy** [comment] 2023-05-03 19:34
Ok, now I can reproduce your error, which is indeed a bug. For historical (ERT-based) reasons, the region with the lowest marker is marked as background region leading to this error. So you have to set `mgr.inv.setRegularization(-1, background=1)` or `mgr.inv.setRegularization(background=1)` (all). However this is not respected if you pass the mesh by `invert(mesh=`, so you have to set the mesh before the inversion to make it run:
```
mgr = tt.Manager(data)
mgr.setMesh(mesh)
mgr.inv.setRegularization(-1, background=False)
velInv = mgr.invert(data, lam=100, useGradient=False)
```
We will correct this behaviour in upcoming versions and leave the issue open until then. Thank you for pointing this out!

**Comment by makeabhishek** [comment] 2023-05-04 13:46
Thanks for the update about the bug. Regarding the velocity, slowness 1/2000 can vary. It was an example I was trying to look. 
Is there any limitation on the high contrast velocity change?

**Comment by makeabhishek** [comment] 2023-05-04 14:02
These velocity range is an arbitrary test data.  But it can be scaled.

**Comment by halbmy** [comment] 2023-05-05 06:36
It looks like the outer ring has a lower velocity and not a higher one.

**Comment by makeabhishek** [comment] 2023-05-05 13:36
It should be higher, but does it make any challenges for a test case?

**Comment by halbmy** [comment] 2023-05-06 06:55
Technically, it does not make a difference but a test case should make sense in a way that you can fit the data, but in your case the data are just not matching the 2000m/s in the outer ring.

As pointed out in my code above, you need to set the mesh BEFORE you set regularization.

**Comment by makeabhishek** [comment] 2023-05-08 21:40
It seems like when not fixing the slowness in regularization, there is no error. However, fixing the slowness values, its giving error. Below is the code snipe and output for both the scenarios. Also, the chi62 value is huge, which looks not converging.

While using this code sipet
```
mgr = tt.TravelTimeManager(data, verbose=True)
mgr.setMesh(mesh)
mgr.inv.setRegularization(1, background=False)
mgr.inv.setRegularization(1, background=False, fix=1/2000)
velInv = mgr.invert(data, lam=100, useGradient=False)
```
Tthe output is:

```
08/05/23 - 15:36:02 - pyGIMLi - INFO - Found 2 regions.
08/05/23 - 15:36:02 - pyGIMLi - INFO - Region with smallest marker set to background (marker=1)
08/05/23 - 15:36:02 - pyGIMLi - ERROR - <class 'pygimli.physics.traveltime.TravelTimeManager.TravelTimeManager'>.checkError(TravelTimeManager.py:93)
DataContainer has no "err" values. Fallback to 3%
08/05/23 - 15:36:02 - pyGIMLi - INFO - Creating forward mesh from region infos.
08/05/23 - 15:36:02 - pyGIMLi - INFO - Creating refined mesh (secnodes: 2) to solve forward task.
08/05/23 - 15:36:02 - pyGIMLi - INFO - Create constant starting model: 0.0008039435736829754
08/05/23 - 15:36:02 - pyGIMLi - INFO - Created startmodel from forward operator: 420 [0.0008039435736829754,...,0.0008039435736829754]
08/05/23 - 15:36:02 - pyGIMLi - INFO - Starting inversion.
08/05/23 - 15:36:02 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

Reset region parameter
RegionManager copying mesh ...0.004 s 
create NeighborInfos ... 0 s 
analysing mesh ... 2 regions.
creating para domain ... 0.001 s
creating para domain ... 0.001 s
ModellingBase::setMesh() copying new mesh ... 0.003 s
FOP updating mesh dependencies ... 0 s
min/max(dweight) = 283447/554908
fop: <pygimli.physics.traveltime.modelling.TravelTimeDijkstraModelling object at 0x7f9fc69ceb30>
Data transformation: <pgcore._pygimli_.RTrans object at 0x7f9fc69ced60>
Model transformation: <pgcore._pygimli_.RTransLog object at 0x7f9fc69ced10>
min/max (data): 6.0e-05/1.2e-04
min/max (error): 3%/3%
min/max (start model): 8.0e-04/8.0e-04
--------------------------------------------------------------------------------

08/05/23 - 15:36:02 - Core - ERROR - There are cells with marker -1. Did you define a boundary region? (This is not needed).
08/05/23 - 15:36:02 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

min/max(dweight) = 283447/554908
Building constraints matrix
constraint matrix of size(nBounds x nModel) 598 x 420
check Jacobian: wrong dimensions: (0x0) should be (120x420)  force: 1
jacobian size invalid, forced recalc: 1
calculating jacobian matrix (forced=1)...*** /home/carsten/miniconda3/envs/build/conda-bld/pgcore_1661190390662/work/gimli/core/src/ttdijkstramodelling.cpp:500	

08/05/23 - 15:36:03 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

... 0.346 s
min data = 6.007e-05 max data = 0.0001176 (120)
min error = 0.03 max error = 0.03 (120)
min response = 0 max response = 0 (120)
calc without reference model
0: rms/rrms(data, response) = 9.14807e-05/100%
0: chi^2(data, response, error, log) = 1111.11
0: Phi = 133333 + 0 * 100 = 133333
Iter: 0
solve CGLSCDWWtrans with lambda = 100

08/05/23 - 15:36:03 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414
08/05/23 - 15:36:04 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

tau = 0. Trying parabolic line search with step length 0.3 ==> tau = 0
 tau < 0.03 ==> tau = 0.03
1: LS newModel: min = 0.000803944; max = 0.000803944
1: LS newResponse: min = 0; max = 0
1: rms/rrms(data, LS newResponse) = 9.14807e-05/100%
1: chi^2(data, LS newResponse, error, log) = 1111.11
1: Phi = 133333+0*100=133333
Linesearch tau = 0.03

08/05/23 - 15:36:04 - Core - ERROR - There are cells with marker -1. Did you define a boundary region? (This is not needed).
08/05/23 - 15:36:04 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

--------------------------------------------------------------------------------
inv.iter 2 ... 1: Model: min = 0.000803944; max = 0.000803944
1: Response: min = 0; max = 0
1: rms/rrms(data, Response) = 9.14807e-05/100%
1: chi^2(data, Response, error, log) = 1111.11
1: Phi = 133333+0*100=133333
calculating jacobian matrix (forced=1)...*** /home/carsten/miniconda3/envs/build/conda-bld/pgcore_1661190390662/work/gimli/core/src/ttdijkstramodelling.cpp:500	

08/05/23 - 15:36:04 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

... 0.38 s
solve CGLSCDWWtrans with lambda = 100

08/05/23 - 15:36:05 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414
08/05/23 - 15:36:05 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

tau = 0. Trying parabolic line search with step length 0.3 ==> tau = 0
 tau < 0.03 ==> tau = 0.03
2: LS newModel: min = 0.000803944; max = 0.000803944
2: LS newResponse: min = 0; max = 0
2: rms/rrms(data, LS newResponse) = 9.14807e-05/100%
2: chi^2(data, LS newResponse, error, log) = 1111.11
2: Phi = 133333+0*100=133333
Linesearch tau = 0.03

08/05/23 - 15:36:05 - Core - ERROR - There are cells with marker -1. Did you define a boundary region? (This is not needed).
08/05/23 - 15:36:05 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

chi² = 1111.11 (dPhi = 0.0%) lam: 100
--------------------------------------------------------------------------------
inv.iter 3 ... 2: Model: min = 0.000803944; max = 0.000803944
2: Response: min = 0; max = 0
2: rms/rrms(data, Response) = 9.14807e-05/100%
2: chi^2(data, Response, error, log) = 1111.11
2: Phi = 133333+0*100=133333
calculating jacobian matrix (forced=1)...*** /home/carsten/miniconda3/envs/build/conda-bld/pgcore_1661190390662/work/gimli/core/src/ttdijkstramodelling.cpp:500	

08/05/23 - 15:36:06 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

... 0.37 s
solve CGLSCDWWtrans with lambda = 100

08/05/23 - 15:36:06 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414
08/05/23 - 15:36:06 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

tau = 0. Trying parabolic line search with step length 0.3 ==> tau = 0
 tau < 0.03 ==> tau = 0.03
3: LS newModel: min = 0.000803944; max = 0.000803944
3: LS newResponse: min = 0; max = 0
3: rms/rrms(data, LS newResponse) = 9.14807e-05/100%
3: chi^2(data, LS newResponse, error, log) = 1111.11
3: Phi = 133333+0*100=133333
Linesearch tau = 0.03

08/05/23 - 15:36:07 - Core - ERROR - There are cells with marker -1. Did you define a boundary region? (This is not needed).
08/05/23 - 15:36:07 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

chi² = 1111.11 (dPhi = 0.0%) lam: 100.0
--------------------------------------------------------------------------------
inv.iter 4 ... 3: Model: min = 0.000803944; max = 0.000803944
3: Response: min = 0; max = 0
3: rms/rrms(data, Response) = 9.14807e-05/100%
3: chi^2(data, Response, error, log) = 1111.11
3: Phi = 133333+0*100=133333
calculating jacobian matrix (forced=1)...*** /home/carsten/miniconda3/envs/build/conda-bld/pgcore_1661190390662/work/gimli/core/src/ttdijkstramodelling.cpp:500	

08/05/23 - 15:36:07 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

... 0.411 s
solve CGLSCDWWtrans with lambda = 100

08/05/23 - 15:36:08 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414
08/05/23 - 15:36:08 - Core - WARNING - ** TMP HACk ** fixing region:  1  to:  17.2414

tau = 0. Trying parabolic line search with step length 0.3 ==> tau = 0
 tau < 0.03 ==> tau = 0.03
4: LS newModel: min = 0.000803944; max = 0.000803944
4: LS newResponse: min = 0; max = 0
4: rms/rrms(data, LS newResponse) = 9.14807e-05/100%
4: chi^2(data, LS newResponse, error, log) = 1111.11
4: Phi = 133333+0*100=133333
Linesearch tau = 0.03
chi² = 1111.11 (dPhi = 0.0%) lam: 100.0
################################################################################
#                 Abort criteria reached: dPhi = 0.0 (< 2.0%)                  #
################################################################################
4: Model: min = 0.000803944; max = 0.000803944
4: Response: min = 0; max = 0
4: rms/rrms(data, Response) = 9.14807e-05/100%
4: chi^2(data, Response, error, log) = 1111.11
4: Phi = 133333+0*100=133333

```
However using
```
mgr = tt.TravelTimeManager(data, verbose=True)
mgr.setMesh(mesh)
mgr.inv.setRegularization(1, background=False)
mgr.inv.setRegularization(1, background=False)
velInv = mgr.invert(data, lam=100, useGradient=False)
```
The output is :
```
08/05/23 - 15:38:42 - pyGIMLi - INFO - Found 2 regions.
08/05/23 - 15:38:42 - pyGIMLi - INFO - Region with smallest marker set to background (marker=1)
08/05/23 - 15:38:42 - pyGIMLi - ERROR - <class 'pygimli.physics.traveltime.TravelTimeManager.TravelTimeManager'>.checkError(TravelTimeManager.py:93)
DataContainer has no "err" values. Fallback to 3%
08/05/23 - 15:38:42 - pyGIMLi - INFO - Creating forward mesh from region infos.
08/05/23 - 15:38:42 - pyGIMLi - INFO - Creating refined mesh (secnodes: 2) to solve forward task.
08/05/23 - 15:38:42 - pyGIMLi - INFO - Create constant starting model: 0.0008039435736829754
08/05/23 - 15:38:42 - pyGIMLi - INFO - Created startmodel from forward operator: 676 [0.0008039435736829754,...,0.0008039435736829754]
08/05/23 - 15:38:42 - pyGIMLi - INFO - Starting inversion.

Reset region parameter
RegionManager copying mesh ...0.004 s 
create NeighborInfos ... 0 s 
analysing mesh ... 2 regions.
creating para domain ... 0.001 s
ModellingBase::setMesh() copying new mesh ... 0.003 s
FOP updating mesh dependencies ... 0 s
min/max(dweight) = 283447/554908
fop: <pygimli.physics.traveltime.modelling.TravelTimeDijkstraModelling object at 0x7f9fc69ce770>
Data transformation: <pgcore._pygimli_.RTrans object at 0x7f9fc6b04040>
Model transformation (cumulative):
	 0 <pgcore._pygimli_.RTransLogLU object at 0x7f9fc6c20e20>
	 1 <pgcore._pygimli_.RTransLogLU object at 0x7f9fc6c20e20>
min/max (data): 6.0e-05/1.2e-04
min/max (error): 3%/3%
min/max (start model): 8.0e-04/8.0e-04
--------------------------------------------------------------------------------
use model trans from RegionManager
min/max(dweight) = 283447/554908
Building constraints matrix
constraint matrix of size(nBounds x nModel) 918 x 676
check Jacobian: wrong dimensions: (0x0) should be (120x676)  force: 1
jacobian size invalid, forced recalc: 1
calculating jacobian matrix (forced=1)...... 0.337 s
min data = 6.007e-05 max data = 0.0001176 (120)
min error = 0.03 max error = 0.03 (120)
min response = 0 max response = 0 (120)
calc without reference model
0: rms/rrms(data, response) = 9.14807e-05/100%
0: chi^2(data, response, error, log) = 1111.11
0: Phi = 133333 + 0 * 100 = 133333
Iter: 0
solve CGLSCDWWtrans with lambda = 100
tau = 0. Trying parabolic line search with step length 0.3 ==> tau = 0
 tau < 0.03 ==> tau = 0.03
1: LS newModel: min = 0.000803944; max = 0.000803944
1: LS newResponse: min = 0; max = 0
1: rms/rrms(data, LS newResponse) = 9.14807e-05/100%
1: chi^2(data, LS newResponse, error, log) = 1111.11
1: Phi = 133333+0*100=133333
Linesearch tau = 0.03
--------------------------------------------------------------------------------
inv.iter 2 ... 1: Model: min = 0.000803944; max = 0.000803944
1: Response: min = 0; max = 0
1: rms/rrms(data, Response) = 9.14807e-05/100%
1: chi^2(data, Response, error, log) = 1111.11
1: Phi = 133333+0*100=133333
calculating jacobian matrix (forced=1)...... 0.331 s
solve CGLSCDWWtrans with lambda = 100
tau = 0. Trying parabolic line search with step length 0.3 ==> tau = 0
 tau < 0.03 ==> tau = 0.03
2: LS newModel: min = 0.000803944; max = 0.000803944
2: LS newResponse: min = 0; max = 0
2: rms/rrms(data, LS newResponse) = 9.14807e-05/100%
2: chi^2(data, LS newResponse, error, log) = 1111.11
2: Phi = 133333+0*100=133333
Linesearch tau = 0.03
chi² = 1111.11 (dPhi = 0.0%) lam: 1002: Model: min = 0.000803944; max = 0.000803944
2: Response: min = 0; max = 0
2: rms/rrms(data, Response) = 9.14807e-05/100%
2: chi^2(data, Response, error, log) = 1111.11

--------------------------------------------------------------------------------
inv.iter 3 ... 2: Phi = 133333+0*100=133333
calculating jacobian matrix (forced=1)...... 0.404 s
solve CGLSCDWWtrans with lambda = 100
tau = 0. Trying parabolic line search with step length 0.3 ==> tau = 0
 tau < 0.03 ==> tau = 0.03
3: LS newModel: min = 0.000803944; max = 0.000803944
3: LS newResponse: min = 0; max = 0
3: rms/rrms(data, LS newResponse) = 9.14807e-05/100%
3: chi^2(data, LS newResponse, error, log) = 1111.11
3: Phi = 133333+0*100=133333
Linesearch tau = 0.03
chi² = 1111.11 (dPhi = 0.0%) lam: 100.0
--------------------------------------------------------------------------------
inv.iter 4 ... 3: Model: min = 0.000803944; max = 0.000803944
3: Response: min = 0; max = 0
3: rms/rrms(data, Response) = 9.14807e-05/100%
3: chi^2(data, Response, error, log) = 1111.11
3: Phi = 133333+0*100=133333
calculating jacobian matrix (forced=1)...... 0.331 s
solve CGLSCDWWtrans with lambda = 100
tau = 0. Trying parabolic line search with step length 0.3 ==> tau = 0
 tau < 0.03 ==> tau = 0.03
4: LS newModel: min = 0.000803944; max = 0.000803944
4: LS newResponse: min = 0; max = 0
4: rms/rrms(data, LS newResponse) = 9.14807e-05/100%
4: chi^2(data, LS newResponse, error, log) = 1111.11
4: Phi = 133333+0*100=133333
Linesearch tau = 0.03
chi² = 1111.11 (dPhi = 0.0%) lam: 100.0
################################################################################
#                 Abort criteria reached: dPhi = 0.0 (< 2.0%)                  #
################################################################################
4: Model: min = 0.000803944; max = 0.000803944
4: Response: min = 0; max = 0
4: rms/rrms(data, Response) = 9.14807e-05/100%
4: chi^2(data, Response, error, log) = 1111.11
4: Phi = 133333+0*100=133333

```

**Comment by halbmy** [comment] 2023-05-09 05:57
I am also having the same fit and also the same TMP Hack message. We need to look into it. At least the original (ERT) region-wise example does not show this error.

**Comment by carsten-forty2** [comment] 2023-05-09 22:35
I can reproduce the problem .. and I will take a look to remove this '** TMP HACk **', which is apparently from me.

**Comment by halbmy** [comment] 2023-05-17 06:18
The code
```
mgr = tt.Manager(data)
mgr.setMesh(mesh)
mgr.inv.setRegularization(1, background=True, fix=1/2000)
velInv = mgr.invert(lam=100, useGradient=False, verbose=True)
```
should be working (a fixed region is a background region), at least it did for me. However, the data fit is bad as the data are apparently not matching to the outer layer of 2000m/s.

**Comment by halbmy** [comment] 2023-05-17 06:33
I suggest using SI units always, i.e. meters instead of centimeters, otherwise the velocity will be cm/s. Please set up the example completely new and check again. Make sure the sensors are nodes in the mesh and not outside. If there are other errors it might make sense to open a new issue and close this one.

**Closed** 2023-06-01 16:20 UTC
