### ISSUE TITLE
Petrophysical Joint Inversion example in Pygimli 1.1

### ISSUE THREAD

**Issue by aurorec** [gimli-org/gimli#250] opened 2020-08-17 09:38 UTC
### Problem description

Hello,

I am currently trying to run the four-phase-inversion example provided for pygimli 1.1 as suggested in the issue #174. I am working with Anaconda and I created a specific environement as suggested in the instructions. 
I managed to run the 4 first steps in code\scripts\field_case but unfortunately I got an issue that I do not manage to solve on the 5th step when running 5_joint_inversion.py. The issue produced is the following :  

  File "C:\Users\a.carrier\.conda\envs\four-phase-inversion\lib\site-packages\fpinv-1.0-py3.7.egg\fpinv\jointmod.py", line 42, in __init__
    self.createConstraints()

  File "C:\Users\a.carrier\.conda\envs\four-phase-inversion\lib\site-packages\fpinv-1.0-py3.7.egg\fpinv\jointmod.py", line 123, in createConstraints
    iid = self._G.addMatrix(self._I)

  File "C:\Users\a.carrier\.conda\envs\four-phase-inversion\lib\site-packages\pygimli\core\matrix.py", line 197, in __BlockMatrix_addMatrix_happy_GC__
    if M.ndim == 1:

AttributeError: 'IdentityMatrix' object has no attribute 'ndim'

It seems that in jointmod.py the  iid = self._G.addMatrix(self._I) need the matrix I to have attributes that she does not have.
The codes used are the ones provided in the example as well as the data. I had to adapt some import lines. I join you the code I try to use on the examples data. 

Thank you very much for your attention,

Best regards

Aurore

### Your environment

**Operating system**: Windows
**Python version**:3.7
**pyGIMLi version**: 1.1.0+31.g47c8d810
**Way of installation**: Conda package

### Code

import numpy as np

import pygimli as pg
from fpinv import FourPhaseModel, JointInv, JointMod
from pybert.manager import ERTManager
from pygimli.physics import Refraction
from pygimli.physics.traveltime.ratools import createGradientModel2D
from settings import *
import pybert as pb
#args = sys.argv
lam = 80
#case = int(args[1])
case=1
weighting = False

if case == 2:
    case = 2
    constrained = True
    mesh = pg.load("mesh_2.bms")
    paraDomain = pg.load("paraDomain_2.bms")
else:
    case = 1
    constrained = False
    mesh = pg.load("mesh_1.bms")
    paraDomain = pg.load("paraDomain_1.bms")

pg.boxprint("Calculating case %s" % case)

# Load meshes and data
#ertScheme = pg.DataContainerERT("ert_filtered.data")
ertScheme = pb.load("ert_filtered.data")

fr_min = 0.1
fr_max = 0.9
phi = np.ones(paraDomain.cellCount()) * poro

# Setup managers and equip with meshes
ert = ERTManager()
#ert.setMesh(mesh)
ert.applyMesh(mesh)
#ert.setData(ertScheme)
ert.applyData(ertScheme)
ert.fop.createRefinedForwardMesh()

#rst = Refraction("rst_filtered.data", verbose=True)
#ttData = rst.dataContainer
rst = pg.physics.traveltime.TravelTimeManager('rst_filtered.data',verbose=True)
ttData=rst.data
#rst.setMesh(paraDomain)
rst.applyMesh(paraDomain)

rst.fop.createRefinedForwardMesh()

# Set errors
ttData.set("err", np.ones(ttData.size()) * rste)
ertScheme.set("err", np.ones(ertScheme.size()) * erte)

if constrained:
    # Find cells around boreholes to fix ice content to zero
    fixcells = []
    for cell in paraDomain.cells():
        x, y, _ = cell.center()
        if (x > 9) and (x < 11) and (y > -depth_5198):
            fixcells.append(cell.id())
        elif (x > 25) and (x < 27) and (y > -depth_5000):
            fixcells.append(cell.id())
    fixcells = np.array(fixcells)
else:
    # Do not fix ice
    fixcells = False

# Setup joint modeling and inverse operators
JM = JointMod(paraDomain, ert, rst, fpm, fix_poro=False, zWeight=zWeight,
              fix_ice=fixcells)

data = pg.cat(ttData("t"), ertScheme("rhoa"))

if weighting:
    n_rst = ttData.size()
    n_ert = ertScheme.size()
    avg = (n_rst + n_ert) / 2
    weight_rst = avg / n_rst
    weight_ert = avg / n_ert
else:
    weight_rst = 1
    weight_ert = 1

error = pg.cat(
    rst.relErrorVals(ttData) / weight_rst,
    ertScheme("err") / weight_ert)

minvel = 1000
maxvel = 5000
velstart = 1 / createGradientModel2D(ttData, paraDomain, minvel, maxvel)
rhostart = np.ones_like(velstart) * np.mean(ertScheme("rhoa"))
fas, fis, fws, _ = fpm.all(rhostart, velstart)
frs = np.ones_like(fas) - fpm.phi
frs[frs <= fr_min] = fr_min + 0.01
frs[frs >= fr_max] = fr_max - 0.01
if fixcells is not False:
    fis[fixcells] = 0.0
startmodel = np.concatenate((fws, fis, fas, frs))

# Fix small values to avoid problems in first iteration
startmodel[startmodel <= 0.001] = 0.001

inv = JointInv(JM, data, error, startmodel, frmin=fr_min, frmax=fr_max,
               lam=lam, maxIter=maxIter)

# Run inversion
model = inv.run()
print(("Chi squared fit:", inv.getChi2()))

# Save results
fwe, fie, fae, fre = JM.fractions(model)
fsum = fwe + fie + fae + fre

print("Min/Max sum:", min(fsum), max(fsum))

rhoest = JM.fpm.rho(fwe, fie, fae, fre)
velest = 1. / JM.fpm.slowness(fwe, fie, fae, fre)

array_mask = np.array(((fae < 0) | (fae > 1 - fre))
                      | ((fie < 0) | (fie > 1 - fre))
                      | ((fwe < 0) | (fwe > 1 - fre))
                      | ((fre < 0) | (fre > 1))
                      | (fsum > 1.01))

np.savez("joint_inversion_%s.npz" % case, vel=np.array(velest),
         rho=np.array(rhoest), fa=fae, fi=fie, fw=fwe, fr=fre, mask=array_mask)

print("#" * 80)
ertchi, _ = JM.ERTchi2(model, error)
rstchi, _ = JM.RSTchi2(model, error, ttData("t"))
print("ERT chi^2", ertchi)
print("RST chi^2", rstchi)
print("#" * 80)

**Comment by florian-wagner** [comment] 2020-08-17 09:43
Dear Aurore,

the original joint inversion as used in the paper was written before we moved to pygimli 1.1. I made the joint inversion code compatible with this new pygimli version in a separate pg1.1 branch https://github.com/florian-wagner/four-phase-inversion/tree/pg1.1 (`git checkout pg1.1`). 

Can you try if it works with this branch?

Best wishes
Florian

**Comment by aurorec** [comment] 2020-08-17 10:32
Hello,

Thank you very much for your quick answer. I tried with this last branch and I still got the same error. Is this possible that I missed something when installing ? I created the conda environnement using the provided .yml. Then in a Gitbash I did "conda active my_environement", then I ran "make all" from the top level of the repository. At this point, in order to run the python codes I had to change some loading functions (the same way than in the code that I provided previously). Do you think it could be the source of the error ? 

Best regards

Aurore

**Comment by florian-wagner** [comment] 2020-08-17 10:39
Did you follow these steps? https://github.com/florian-wagner/four-phase-inversion#quick-example-combining-the-steps-above ?

For example it should be `conda activate four-phase-inversion`, not `conda active my_environement`.

Cheers
Florian

**Comment by aurorec** [comment] 2020-08-17 11:02
Hello,

Yes, I wrote my_environment as a generalisation (sorry if it was not clear) but it is four-phase-inversion for me indeed. In a python shell I can perform "import fpinv" and I see all the modules. 
I redo everything to be sure and I still got this in my GitBash (it seems that I have more information here than from spyder previously) : 

python 5_joint_inversion.py 1
fatal: not a git repository (or any of the parent directories): .git
17/08/20 - 12:58:53 - pyGIMLi - INFO - Found 2 regions.
17/08/20 - 12:58:53 - pyGIMLi - INFO - Region with smallest marker set to background (marker=1)
Reset region parameter
RegionManager copying mesh ...0.006 s
create NeighborInfos ... 0.009 s
analysing mesh ... 1 regions.
creating para domain ... 0.016 s
17/08/20 - 12:58:53 - pyGIMLi - INFO - Found 1 regions.
17/08/20 - 12:58:53 - pyGIMLi - INFO - Using smoothing with zWeight = 0.25.
Error!: C:/msys64/home/halbm/gimli/gimli/core/src/regionManager.cpp: 844       void GIMLI::RegionManager::fillConstraintWeights(GIMLI::RVector&)  in use??
################################################################################
#                              Calculating case 1                              #
################################################################################
<class 'pygimli.physics.ert.ert.ERTManager'>.applyMesh(C:\Users\a.carrier\.conda\envs\four-phase-inversion\lib\site-packages\pygimli\frameworks\methodManager.py:647) : Mesh: Nodes: 2518 Cells: 4766 Boundaries: 7283
Traceback (most recent call last):
  File "5_joint_inversion.py", line 74, in <module>
    fix_ice=fixcells)
  File "C:\Users\a.carrier\.conda\envs\four-phase-inversion\lib\site-packages\fpinv-1.0-py3.7.egg\fpinv\jointmod.py", line 42, in __init__
  File "C:\Users\a.carrier\.conda\envs\four-phase-inversion\lib\site-packages\fpinv-1.0-py3.7.egg\fpinv\jointmod.py", line 123, in createConstraints
  File "C:\Users\a.carrier\.conda\envs\four-phase-inversion\lib\site-packages\pygimli\core\matrix.py", line 197, in __BlockMatrix_addMatrix_happy_GC__
    if M.ndim == 1:
AttributeError: 'IdentityMatrix' object has no attribute 'ndim'
make[1]: *** [Makefile:13: joint1] Error 1
make[1]: Leaving directory 'C:/Users/a.carrier/Desktop/InitiationPygimliBERT/four-phase-inversion-pg1.1/code/scripts/field_case'
make: *** [Makefile:33: results] Error 2
(four-phase-inversion)

**Comment by aurorec** [comment] 2020-08-31 13:11
Hello,

I finally managed to get the code running by using the pygimli core in developpement and by setting ert.fop.setData(ertScheme) and rst.fop.setData(ttData). However, I got some warnings such as:
- Error! no cWeights defined. You should create constraint matrix first => Then I added JM.createConstraints() and inv.setCWeight(JM.cWeight)

The inversion now runs but clearly diverges. I join you the result of the last iteration as well as the warnings and the portion of code that I had to adapt to make the code run. I am wondering if the constraint matrix and/or roughness matrix are properly computed or if I declared something bad when trying to adapt the input to the new pygimli version. Note that the independant inversions run properly and the result of the 4PM associated is consistent with the results of the paper.


_Iteration: 17 | Chi^2: 25515.79 | RMS: 5.80%                 
Phi / oldphi 1.019238368396317
Done. Reached data fit criteria of delta phi < 0.25%.
('Chi squared fit:', 25515.793338629428)
Min/Max sum: 0.3987206608421481 1.8888837384124186
Mesh: Nodes: 2007 Cells: 3704 Boundaries: 5710 secNodes: 11420
Mesh: Nodes: 9801 Cells: 19064 Boundaries: 14566
Min. | Max.
 Water: 0.00 | 0.83
 Ice:   0.00 | 0.67
 Air:   0.00 | 1.00
 Rock:  0.10 | 0.87
 SUM:   0.40 | 1.89
 Rho:   6.76e+01 | 1.70e+08
 Vel:   258 | 7090
Calculating response for model: min = 67.5647 max = 1.70269e+08
Using existing primary potentials.
Forward: time: 3.696s
Response: min = 671.778 max = 1710.71
Reciprocity rms(modelReciprocity) 8.35949%, max: 46.5223%
Mesh: Nodes: 2007 Cells: 3704 Boundaries: 5710 secNodes: 11420
Mesh: Nodes: 9801 Cells: 19064 Boundaries: 14566
 Min. | Max.
 Water: 0.00 | 0.83
 Ice:   0.00 | 0.67
 Air:   0.00 | 1.00
 Rock:  0.10 | 0.87
 SUM:   0.40 | 1.89
 Rho:   6.76e+01 | 1.70e+08
 Vel:   258 | 7090
Calculating response for model: min = 67.5647 max = 1.70269e+08
Using existing primary potentials.
Forward: time: 3.248s
Response: min = 671.778 max = 1710.71
Reciprocity rms(modelReciprocity) 8.35949%, max: 46.5223%
ERT chi^2 8.023070286825293
RST chi^2 29919.814244604764_


What's more, I got some warning during the creation of FPM:


_Calculating case 1
31/08/20 - 14:40:57 - pyGIMLi - ?[0;32;49mINFO?[0m - Found 2 regions.
31/08/20 - 14:40:57 - pyGIMLi - ?[0;32;49mINFO?[0m - Region with smallest marker set to background
 (marker=1)
31/08/20 - 14:40:57 - pyGIMLi - ?[0;32;49mINFO?[0m - Found 2 regions.
31/08/20 - 14:40:57 - pyGIMLi - ?[0;32;49mINFO?[0m - Region with smallest marker set to background
 (marker=1)
Reset region parameter
RegionManager copying mesh ...0.007 s
create NeighborInfos ... 0.01 s
analysing mesh ... 1 regions.
creating para domain ... 0.015 s
31/08/20 - 14:40:57 - pyGIMLi - ?[0;32;49mINFO?[0m - Found 1 regions.
Reset region parameter
RegionManager copying mesh ...0.006 s
create NeighborInfos ... 0.009 s
analysing mesh ... 1 regions.
creating para domain ... 0.015 s
31/08/20 - 14:40:57 - pyGIMLi - ?[0;32;49mINFO?[0m - Found 1 regions.
31/08/20 - 14:40:57 - pyGIMLi - ?[0;32;49mINFO?[0m - Using smoothing with zWeight = 0.25.
Error!: C:/msys64/home/halbm/gimli/gimli/core/src/regionManager.cpp: 844                void GIMLI
::RegionManager::fillConstraintWeights(GIMLI::RVector&)  in use??
31/08/20 - 14:40:57 - pyGIMLi - ?[0;32;49mINFO?[0m - Using smoothing with zWeight = 0.25.
Error!: C:/msys64/home/halbm/gimli/gimli/core/src/regionManager.cpp: 844                void GIMLI
::RegionManager::fillConstraintWeights(GIMLI::RVector&)  in use??
WARNING: 1271 of 3704 fraction values are unphysical.
min/max(dweight) = 33.3333/2.25225e+06
31/08/20 - 14:40:57 - pyGIMLi - ?[0;32;49mINFO?[0m - Using smoothing with zWeight = 0.25.
Error!: C:/msys64/home/halbm/gimli/gimli/core/src/regionManager.cpp: 844                void GIMLI
::RegionManager::fillConstraintWeights(GIMLI::RVector&)  in use??
min/max(cWeight) = 0.25/1
model 0.001 0.47_

Here is the loading part of the code that I had to modify:

```
ert=ERTManager("ert_filtered.data")
ertScheme=ert.data

fr_min = 0.1
fr_max = 0.9
phi = np.ones(paraDomain.cellCount()) * poro
#Setup Manager and equip with meshes
#ert = ERTManager()
#ert.setMesh(mesh)
#ert.setData(ertScheme)
ert.applyMesh(mesh)
#ert.setData(ertScheme)
ert.fop.createRefinedForwardMesh()
ert.fop.setData(ertScheme)
ert.fop.setMesh(mesh)
#rst = Refraction("rst_filtered.data", verbose=True)
#ttData = rst.dataContainer
rst = pg.physics.traveltime.TravelTimeManager("rst_filtered.data",verbose=True)
rst.data.markInvalid( rst.data('t') == 0)

rst.data.removeInvalid()
ttData = rst.data
#rst.setMesh(paraDomain)
rst.applyMesh(paraDomain)
rst.fop.createRefinedForwardMesh()
rst.fop.setData(ttData)
rst.fop.setMesh(paraDomain)
```

Thank you very much for your help.

Best regards,

Aurore

**Comment by florian-wagner** [comment] 2020-10-09 11:36
Dear @aurorec,

sorry for being so unresponsive last month. Glad to hear that you generally got it working. The first warning you mention can be ignored, I think I had it, too. But yes, that is misleading and should be fixed. But the fact that the inversion is diverging can have many reasons. Are you trying to reproduce an example from the paper/code repository or are you trying to invert your own data? Happy to help, we can also discuss via email (florian.wagner@eonerc.rwth-aachen.de), but I think I will close this here, since it's not a pygimli issue, but a rather related to the separate joint inversion code.

Cheers
Florian

**Closed by florian-wagner** 2020-10-09 11:36 UTC

**Comment by Yonatan-geo** [comment] 2021-05-26 14:49
Dear Florian-Wagner (Dr.);

I am (Yonatan) trying to run the four-phase-inversion example provided using pygimli as suggested in issue #174.
I thank you very much in advance for your time and attention.
**For synthetic_case**; the first step run without any error, but I got the following error in the second step, and other steps are not working.

runfile('C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case/2_create_syn_data.py', wdir='C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case')
################################################################################
#                       Simulate apparent resistivities                        #
################################################################################
Warning! DataSchemeBase::create has unhandled arguments
{'spacings': [1, 2, 4]}
26/05/21 - 22:26:28 - pyGIMLi - INFO - Found 2 regions.
26/05/21 - 22:26:28 - pyGIMLi - INFO - Region with smallest marker (1) set to background
Traceback (most recent call last):

  File "C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code\scripts\synthetic_case\2_create_syn_data.py", line 40, in <module>
    ertData = ert.simulate(meshERTFWD, res, ertScheme, noiseLevel=0.01, noiseAbs=0.0)

  File "C:\Users\pingyuc\anaconda3\envs\Pg_Bert\lib\site-packages\pygimli\physics\ert\ert.py", line 790, in simulate
    elif hasattr(res[0], '__iter__'):  # ndim == 2

  File "C:\Users\pingyuc\anaconda3\envs\Pg_Bert\lib\site-packages\pygimli\core\datacontainer.py", line 55, in __DC_getVal
    if self.isSensorIndex(key):

ArgumentError: Python argument types in
    None.isSensorIndex(DataContainerERT, int)
did not match C++ signature:
    isSensorIndex(GIMLI::DataContainer {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > token)
##

**For the Third step I found this:**

runfile('C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case/3_conventional_inversion.py', wdir='C:/Users/pingyuc/Desktop/Four_phase/four-phase-inversion/four-phase-inversion-pg1.1/code/scripts/synthetic_case')
Traceback (most recent call last):

  File "C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code\scripts\synthetic_case\3_conventional_inversion.py", line 18, in <module>
    case = int(sys.argv[1])

IndexError: list index out of range


_**For information I used:**_

**conda info**

(pg_Bert) C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code>conda info

     active environment : pg_Bert
    active env location : C:\Users\pingyuc\anaconda3\envs\pg_Bert
            shell level : 2
       user config file : C:\Users\pingyuc\.condarc
 populated config files : C:\Users\pingyuc\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages :
       base environment : C:\Users\pingyuc\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/gimli/win-64
                          https://conda.anaconda.org/gimli/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\pingyuc\anaconda3\pkgs
                          C:\Users\pingyuc\.conda\pkgs
                          C:\Users\pingyuc\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\pingyuc\anaconda3\envs
                          C:\Users\pingyuc\.conda\envs
                          C:\Users\pingyuc\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

**python -c "import pygimli; print(pygimli.version); import fpinv"**

(pg_Bert) C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code>python -c "import pygimli; print(pygimli.version); import fpinv"
<function version at 0x000001E60D51C048>

**conda env update --file environment.yml**

EnvironmentFileNotFound: 'C:\Users\pingyuc\Desktop\Four_phase\four-phase-inversion\four-phase-inversion-pg1.1\code\environment.yml' file not found

**I used** 

# Name                   Version               Build  Channel
pygimli                   1.1.1                    py37_0    gimli
pybert                    2.3.1                    py37_0    gimli

**Comment by florian-wagner** [comment] 2021-07-12 19:22
Dear @get1001,

sorry for the late reply. This issue somewhat got lost as it was already closed (better open a new one next time). If the problem still remains, can you please submit an issue here: https://github.com/florian-wagner/four-phase-inversion/issues

Kind regards
Florian
