### ISSUE TITLE
Conda packages for Mac OS?

### ISSUE THREAD

**Issue by ev510** [gimli-org/gimli#201] opened 2019-10-14 08:46 UTC
### Problem description

Hello. 
Is any progress on Conda packages for Mac? I'm a happy user of BERT, but always access through university cluster. I am now trying to get some students using BERT on their personal computers (and mine), and I haven been repeatedly thwarted trying to install on a Mac. I've tried the Mac install suggestions with no success, details below.
Thanks,
Emily

### Your environment

**Operating system**: Mac 10.14.6
**Python version**: 3.6
**pyGIMLi version**: 
**Way of installation**: Attempting to follow Mac installation instructions 

From here:
https://www.pygimli.org/installation.html (Mac OS) and here:
 https://github.com/gimli-org/gimli/issues/46#issuecomment-357735129

### Steps to reproduce
First problem occurs here: "brew install boost --with-python3"

### Expected behavior
Install package, and I could move on with installation.

### Actual behavior
```
Error: invalid option: --with-python3
```

When I try to continue with the later steps, it's seems that boost install issues are cause for (some of) the trouble.

**Comment by florian-wagner** [comment] 2019-11-15 09:26
Hi Emily,

the problem is that none of the developers owns a Mac and we cannot test this. I have some new colleagues with Macs now and will ask them to try and build a conda package.

We leave this open as a reminder and keep you posted.

Cheers
Florian

**Comment by florian-wagner** [comment] 2020-05-11 08:07
Dear Mac users,

pyGIMLi 1.1 is out and (finally) available for Mac OS as a conda package.

Can you try `conda create -n pg -c gimli -c conda-forge pygimli=1.1.0` (see instructions here https://www.pygimli.org/installation.html) and please let us know if it works so we can close this issue?

Thanks a lot

**Comment by florian-wagner** [comment] 2020-05-11 08:11
CC @AlainPlattner @aurorec @eclyne @ivasconcelosUU @diegozain @hanafusman

**Comment by ev510** [comment] 2020-05-11 08:34
Wahoo! Thank you!

I was able to install very easily on my Mac.

Thank you for the hard work all of you have put into this!

Looking forward to working on many more projects with it.

**Comment by florian-wagner** [comment] 2020-05-11 08:59
Thank you Emily.

**Closed by florian-wagner** 2020-05-11 08:59 UTC

**Comment by Priyamomer** [comment] 2021-02-18 02:01
It is very easy to install pygimli i was also having problems but the key steps of installation of pygimli in macos are:
1. Open a terminal Mac OS and write:

conda create -n pg -c gimli -c conda-forge pygimli=1.1.0

2.Write the statement on mac terminal: conda activate pg
How the hard one it took some to me to figure it out
3.How go to enivorment in anaconda 
<img width="493" alt="Screenshot 2021-02-18 at 7 29 36 AM" src="https://user-images.githubusercontent.com/20286633/108294072-234cf080-71bb-11eb-855d-90ff68459bde.png">
4. then click on it and you will see option  as :
<img width="669" alt="Screenshot 2021-02-18 at 7 29 44 AM" src="https://user-images.githubusercontent.com/20286633/108294118-3fe92880-71bb-11eb-883d-8c0014837f30.png">
That's it now you can easily open the pygimli with the coding interface of your choice!!
