### ISSUE TITLE
How to improve crosshole traveltime interface characterization?

### ISSUE THREAD

**Issue by 728236958** [gimli-org/gimli#456] opened 2022-10-27 15:29 UTC
### Problem description
How to improve crosshole traveltime interface characterization?
1. Considering the limited depth of surface seismic rays, we consider to use crosshole seismic testing. However, the crosshole characterization of the surface is still unsatisfactory. Here we try case 3 and case 4 in transform2021.The resolution of the lower inclined interface is not ideal.
![image](https://user-images.githubusercontent.com/69100178/198325549-fa1a8168-7c7d-49ae-89df-c1264f73a994.png)
![image](https://user-images.githubusercontent.com/69100178/198330491-319470af-892f-4058-aff6-727ac714355b.png)

2. If we set noiseLevel=0 or a very small value, chi2 is difficult to converge to 1.

### Your environment
**Operating system**: Windows
**pyGIMLi version**: 1.3.0
**Way of installation**: Conda package

### Steps to reproduce
[geometry.poly](https://github.com/gimli-org/gimli/files/9880645/geometry.poly)
```import matplotlib.pyplot as plt
plt.style.use("seaborn-notebook")
%config InlineBackend.figure_format='svg'
import pygimli as pg
import numpy as np
import pygimli.meshtools as mt
import pygimli.physics.traveltime as tt
geometry = mt.readPLC("C:/Users/Dell/data/geometry.poly")
geometry.scale([0.5, 1, 1])
ax, _ = pg.show(geometry)
#bolehole
n = 20 
borehole = np.ones((n, 2)) * 10 
borehole[:,1] = np.linspace(-.5, -23, n) 
sensors = np.vstack([borehole] * 2)
sensors[n:,0] *= -1 

ax.plot(sensors[:,0], sensors[:,1], "ko")
ax.figure
for pos in sensors:
    geometry.createNode(pos)
# create mesh    
mesh = mt.createMesh(geometry, quality=33.5, area=1)
ax, _ = pg.show(mesh, markers=True, showMesh=True)
ax.plot(sensors[:,0], sensors[:,1], "mo");

#scheme
scheme = tt.createCrossholeData(sensors)
print(scheme)
print(scheme.sensor(0))
np.column_stack((pg.x(scheme), pg.y(scheme)))

v = np.array([800,500,1000,2000])[mesh.cellMarkers()] # Velocities for 4 markers

ax, _ = pg.show(mesh, v, label=pg.unit("vel"));

shots = scheme["s"]
geophones = scheme["g"]

for s, g in zip(shots, geophones):
    ray = np.array([s, g])
    ax.plot(sensors[ray, 0], sensors[ray, 1], "w-", lw=0.5)

mgr = tt.TravelTimeManager()
data = mgr.simulate(mesh=mesh, scheme=scheme, slowness=1/v,
                   secNodes=4, noiseLevel=0.001, noiseAbs=1e-6, seed=1337)
print(data)

np.column_stack((data["s"], data["g"], data["t"]))[:12]
from pygimli.viewer.mpl import showVecMatrix
def showCrossholeData(data, vals, **kwargs):
    d = -pg.y(data)  # sensor depth
    ds = d[data["s"]]  # shot depth
    dg = d[data["g"]]  # geophone depth
    ax, cb = showVecMatrix(ds, dg, vals, label="apparent velocity (m/s)", **kwargs);
    ax.set_xlabel("shot depth");
    ax.set_ylabel("geophone depth");

showCrossholeData(data, data["t"])
# refined grid
x = np.linspace(min(pg.x(data)), max(pg.x(data)), 45)
y = np.linspace(min(pg.y(data)), max(pg.y(data)), 57)
grid = pg.meshtools.createMesh2D(x, y)
ax, cb = pg.show(grid)
ax.plot(list(pg.x(data)), list(pg.y(data)), "ro");

mgr = tt.TravelTimeManager(data)
mgr.invert(data, mesh=grid, 
           startModel=0.001,
           useGradient=False,
           #zWeight=1,
           secNodes=3,
           lam=20,
           verbose=True)
mgr.showResult();
ax, cb = mgr.showResult(cMin=500, cMax=2000);
mgr.drawRayPaths(ax);
```
### My example is as follows: Takes a long time to run.
[testd0.csv](https://github.com/gimli-org/gimli/files/9880693/testd0.csv)
```
#2D cross-borehole seismic forward and inversion
import numpy as np
import pygimli as pg
import pygimli.meshtools as mt
import matplotlib.pyplot as plt
from pygimli.physics import TravelTimeManager
from pygimli.viewer import showMesh
import pygimli.physics.traveltime as tt
import pandas as pd

# create mesh
mesh = mt.createGrid(x=np.arange(120.1),y=-np.arange(60.1),worldBoundaryMarker=True)
_= pg.show(mesh, markers=True, showMesh=True)
print(mesh)
#bolehole
bh_spacing = 50.0
bh_length = 50.0
sensor_spacing = 2
depth = -np.arange(sensor_spacing, bh_length + sensor_spacing, sensor_spacing)
sensors = np.zeros((len(depth) * 2, 2))  # two boreholes
sensors[:len(depth), 0] = 10  # x
sensors[len(depth):, 0] = 10 + bh_spacing  # x
sensors[:, 1] = np.hstack([depth] * 2)  # y
print(sensors)
ax, _ = pg.show(mesh, markers=True, showMesh=True)
ax.plot(sensors[:,0], sensors[:,1], "mo")
#import velocity value
test_path="C:/Users/Dell/Desktop/testd0.csv"
f=open(test_path,encoding="utf-8")
test=pd.read_csv(f,low_memory=False,header=None)
test=np.array(test).reshape(1,-1).squeeze(0)
print(test)
vp = test
print(len(test))
pg.show(mesh, data=vp, label='v in m/s', showMesh=True)
#scheme
scheme = tt.createCrossholeData(sensors)
print(scheme)
print(scheme.sensor(0))
np.column_stack((pg.x(scheme), pg.y(scheme)))
print(scheme["valid"])
ax, _ = pg.show(mesh, vp, label=pg.unit("vel"));
ax.set_xlim(0, 100);
ax.set_ylim(-60, 0);

shots = scheme["s"]
geophones = scheme["g"]

for s, g in zip(shots, geophones):
    ray = np.array([s, g])
    ax.plot(sensors[ray, 0], sensors[ray, 1], "w-", lw=0.5)
print(ray)

#simulate
mgr = tt.TravelTimeManager()
data = mgr.simulate(mesh=mesh, scheme=scheme, slowness=1/vp,
                   secNodes=4, noiseLevel=0.001, noiseAbs=1e-6, seed=1337)
print(data)
data.save("traveltimedcgz00.dat")
from pygimli.viewer.mpl import showVecMatrix
showVecMatrix(data["s"],data["g"],data["t"]);
#invert
mgr = tt.TravelTimeManager(data)
mgr.invert(data, mesh=mesh, 
           useGradient=True,
           zWeight=1,
           secNodes=4,vTop=2000, vBot=4000,
           lam=10,
           verbose=True)
mgr.showResult();
#output show
ax,_= mgr.showResult(cMin=2000, cMax=4000);
pg.show(geom,ax=ax, fillRegion=False, regionMarker=False)
ax.set_xlim(0, 100);
ax.set_ylim(-60, 0);
#mgr.drawRayPaths(ax);
```

**Comment by 728236958** [comment] 2022-10-27 15:34
How can I improve it to achieve the resolution more accurately? At the same time, we imitate example02. The inversion result is not as ideal as that in the case. How can I improve it to achieve the resolution more accurately? 
![image](https://user-images.githubusercontent.com/69100178/198333275-944887e2-eb7d-431a-acd4-e8ac6430210c.png)

```
import pygimli as pg
import pygimli.meshtools as mt
import matplotlib.pyplot as plt
import numpy as np
from pygimli.physics.traveltime import TravelTimeManager,createCrossholeData
import pygimli.physics.traveltime as tt
world = mt.createWorld(start=[-50, 0], end=[50, -50], worldMarker=True)
c1 = mt.createCircle(pos=(0, -2.0),radius=15, start=1.25*math.pi, end=1.75*math.pi,isClosed=True, marker = 2, area=1)
c2 = mt.createCircle(pos=(-15, -15.0),radius=15, start=1.25*math.pi, end=1.75*math.pi,isClosed=True, marker = 2, area=1)
c3 = mt.createCircle(pos=(18, -20.0),radius=15, start=1.25*math.pi, end=1.75*math.pi,isClosed=True, marker = 2, area=1)
geom = c1+c2+c3+world   createworld
pg.show(geom)
n = 20   
borehole = np.ones((n, 2)) * 30   
borehole[:,1] = np.linspace(-1, -48, n) 
sensors = np.vstack([borehole] * 2)
sensors[n:,0] *= -1 
for pos in sensors:
    geom.createNode(pos)
scheme = createCrossholeData(sensors)   
scheme.setSensors(pos)
from pygimli.viewer import showMesh
mesh = mt.createMesh(geom, 
                     area=5.0,
                     quality=33,
                     smooth=[2, 4] # [0:no smoothing or 1:node center or 2:weighted node center, # of iter]
                    )
ax, _ = pg.show(mesh, markers=True, showMesh=True)
ax.plot(sensors[:,0], sensors[:,1], "mo")
scheme = tt.createCrossholeData(sensors)
print(scheme)
print(scheme.sensor(0))
np.column_stack((pg.x(scheme), pg.y(scheme)))
v = np.array([0,2400,1200,0])[mesh.cellMarkers()] 
ax, _ = pg.show(mesh, v, label=pg.unit("vel"));

shots = scheme["s"]
geophones = scheme["g"]

for s, g in zip(shots, geophones):
    ray = np.array([s, g])
    ax.plot(sensors[ray, 0], sensors[ray, 1], "w-", lw=0.5)
mgr = tt.TravelTimeManager()
data = mgr.simulate(mesh=mesh, scheme=scheme, slowness=1/v,
                   secNodes=4, noiseLevel=0.001, noiseAbs=1e-6, seed=1337)
print(data)
data.save("fjzkk.dat")
x = np.linspace(min(pg.x(data)),max(pg.x(data)),50)
y = np.linspace(min(pg.y(data)),max(pg.y(data)),40)
grid = pg.meshtools.createMesh2D(x,y)
ax,cb = pg.show(grid)
ax.plot(list(pg.x(data)), list(pg.y(data)), "ro");
mgr = tt.TravelTimeManager(data)
mgr.inv.inv.setRecalcJacobian(True)
mgr.invert(data,mesh = grid,
           startModel=0.001,
           useGradient=False,secNodes=4,lam=1000, zWeight=1.0,
           verbose=True)
ax, cb = mgr.showResult(cMin=1200, cMax=2400);
mgr.drawRayPaths(ax);
pg.show(geom,ax=ax, fillRegion=False)
ax.set_xlim(-30, 30);
ax.set_ylim(-48, -1);
```
**Thank you very much！**

**Comment by halbmy** [comment] 2022-11-01 12:44
Dear pyGIMLi user (we don't even know your name only),
obviously you did some computations with some results and you are unhappy with it. So you paste your code and hope that somebody will solve your problem. The problem is that you did not lay out your problem. The question

> How can I improve it to achieve the resolution more accurately?
can hardly (even if posed twice) motivate one of the developers or other users to try your problem.

In the issue, you should show the synthetic model, the synthetic data, the inversion result step by step so that the reader can understand what exactly your problem is. Am I right that you have two completely different cases?

Just a comment to the single concrete question
> If we set noiseLevel=0 or a very small value, chi2 is difficult to converge to 1.

The chi-square value is the mean quadratic misfit, weighted by the error. If the noise level is zero, this leads to infinite values. 

A synthetic experiment should always be done with realistic noise of a known error model that is used in the inversion.

**Comment by 728236958** [comment] 2022-11-01 15:56
Thank you very much for your reply. I'm sorry for not being clear enough and pasting too much code.

There are really two problems. They correspond to Case 4 in [transform 2021](https://github.com/gimli-org/transform2021/blob/main/4_Traveltime_inversion.ipynb), and [plot_02](https://www.pygimli.org/_examples_auto/2_seismics/plot_02_crosshole_tomography.html#sphx-glr-examples-auto-2-seismics-plot-02-crosshole-tomography-py)

For the first question, I refined the grid in the case, because the previous grid cannot depict the following slope. I guess that the upper interface and the middle circular unit in the case may interfere with the depiction of the lower inclined plane, so we try to depict only one fault (sorry, we used our own case instead of a simple test). The result is that the portrayal effect does not conform to the actual situation, and it should be earlier than the actual situation.
![image](https://user-images.githubusercontent.com/69100178/199276215-99ebad19-7d28-4361-8772-b4be8dbcc4e6.png)
![image](https://user-images.githubusercontent.com/69100178/199277394-33bf5d30-d004-4769-8d96-c94520e5c947.png)
Our case
![image](https://user-images.githubusercontent.com/69100178/199277921-4f983710-bb62-4716-858e-9b1d650983b1.png)

Second question, we hope to accurately depict the three elements as in plot_02, but the actual results are not ideal.
![image](https://user-images.githubusercontent.com/69100178/199278228-30d3c3b5-6c90-4f8b-9c09-1bd92a6a3510.png)

**Comment by halbmy** [comment] 2023-05-02 08:34
I am sorry for not getting back to you for half a year. Reason is that the case seems to be very specific I did not
1. understand the actual problem (except that the result was different from your expectation), and
2. have the time to did through the extensive scripts

If you are able to fit the data, you obtained one of the possible solutions. If this does not meet your expectations, you should change your regularization or improve your experimental design to have a better resolution.

I am closing this issue. If you can break down the problem to something simpler, just raise another issue and we might have a new look.

**Closed by halbmy** 2023-05-02 08:34 UTC

**Comment by 728236958** [comment] 2023-05-03 07:31
Thank you for your reply, we will improve the problem before asking questions！
