### ISSUE TITLE
different Geometric factor for same configration.

### ISSUE THREAD

**Issue by nbillybgkv** [gimli-org/gimli#466] opened 2022-11-18 07:52 UTC
The same configuration let say DD3 has different geometric factor ? I think It should be the same geometric factor for one configuration given that the geometric factor only depends on the geometry of the bucket (i.e. location of electrodes).
<img width="323" alt="Capture2" src="https://user-images.githubusercontent.com/108271669/202648722-e3461a76-02ae-4317-b6aa-d4b9bc60ad46.PNG">

**Comment by halbmy** [comment] 2022-11-21 20:07
Dear pyGIMLi user,
how could anyone give a meaningful comment to your very sparse details? Please describe how you obtained the image.
From the word bucket I suspect you're working on a bounded domain with a 3D distribution of electrodes? In this case a 2D pseudosection will probably not make much sense, I would prefer `showDataContainerAsMatrix`.
Thomas

**Comment by halbmy** [comment] 2022-11-22 07:09
So the electrodes have been linearly arranged, even though as rings?

How did you account for the ring electrodes and how did you compute the geometric factors?

**Comment by nbillybgkv** [comment] 2022-11-22 09:51
yes. they were arranged linearly,the geometric factor was calculted,
data["k"] = pg.Vector(data.size(), 1.0) 
out = ert.simulate(mesh=mesh, scheme=data, res=1.0, calcOnly=True)
print(out)
data["k"] = 1.0 / out["u"]

**Comment by halbmy** [comment] 2022-11-22 10:57
Actually, you can ease this procedure by:
```
from pygimli.physics import ert
data["k"] = ert.createGeometricFactors(data, mesh=mesh)
```
By the keyword arguments `h2` and `p2` (both True by default) you can control whether the mesh is further refined or quadratic shape functions are to be used, respectively, to achieve a higher numerical accuracy. Can you try this?

**Comment by halbmy** [comment] 2022-12-05 13:34
I am closing this as the problem (different Geometric factor for same configuration) was just caused by visualizing 3D data with a 2D routine. At any rate, such a pseudosection is (like `showDataContainerAsMatrix`) just a graphical data representation and does not induce any statements on subsurface or equivalency of data.

**Closed by halbmy** 2022-12-05 13:34 UTC
