### ISSUE TITLE
Alternative ERT Schemes?

### ISSUE THREAD

**Issue by Coastal0** [gimli-org/gimli#115] opened 2017-12-13 03:54 UTC
Hi guys,

Are there any other options for the `ert.createERTData` schemes at this point in time?

I can make sequences using other softwares (e.g. Electre2) and try to integrate them somehow, but I thought you might have a better idea or implementation already existing.

**Comment by florian-wagner** [comment] 2017-12-13 04:29
Hi Alex,

`createData` supports the common array types used in ERT. If you have something more complex, you can always create an empty data container and fill it manually. In the example below I created an `abmn` function, which creates a comprehensive data set. But you can replace this function by anything else (e.g., an Electre2 importer).

Hope that helps, Florian

``` python
import pybert as pb
import numpy as np
import itertools

def abmn(n):
    """
    Construct all possible four-point configurations for a given
    number of sensors after Noel and Xu (1991).
    """
    combs = np.array(list(itertools.combinations(list(range(1, n+1)), 4)))
    perms = np.empty((int(n*(n-3)*(n-2)*(n-1)/8), 4), 'int')
    print(("Comprehensive data set: %d configurations." % len(perms)))
    for i in range(np.size(combs, 0)):
        perms[0+i*3, :] = combs[i,:] # ABMN
        perms[1+i*3, :] = (combs[i, 0], combs[i, 2], combs[i, 3], combs[i, 1]) #AMNB
        perms[2+i*3, :] = (combs[i, 0], combs[i, 2], combs[i, 1], combs[i, 3]) #AMBN

    return perms - 1

# Create empty DataContainer
data = pb.DataContainerERT() 

# Add electrodes
n = 16
spacing = 1.5
for i in range(16):
    data.createSensor([i * spacing, 0.0]) # 2D, no topography

# Add configurations
cfgs = abmn(n) # create all possible 4P cgfs for 16 electrodes
for i, cfg in enumerate(cfgs):
    data.createFourPointData(i, *map(int, cfg)) # (We have to look into this: Mapping of int necessary since he doesn't like np.int64?)

# Optional: Save in unified data format for use with command line apps
data.save("data.shm", "a b m n")
```

**Comment by florian-wagner** [comment] 2017-12-13 04:33
P.S.: Also works for the pygimli DataContainer.

**Comment by Coastal0** [comment] 2017-12-13 04:58
Ah, great! 

Thanks Florian.

**Comment by halbmy** [comment] 2017-12-13 07:18
I was always annoyed by the int casts, but the *map is a great pythonic solution!
Anyway most people will not know about it, so we should try to make it compatible with np.int64 or even a list (casted into an IVector).

**Comment by halbmy** [comment] 2017-12-13 07:19
The script does NOT work for the pg.DataContainer, but I guess you mean pg.DataContainerERT

**Comment by florian-wagner** [comment] 2017-12-14 04:36
@Coastal0 So we can close this?
@halbmy Yes, pg.DataContainerERT, but with some minor modifications (registering sensor tokens), it should also be applicable to the general DataContainer, right? And yes, I agree, enabling np.int54 support would be the most elegant solution.

**Comment by halbmy** [comment] 2017-12-14 07:12
@Coastal0 yes
@florian-wagner No, `createFourPointData` just exists for `pg.DataContainerERT` but as this data container is in pygimli anyway, why not taking it...

**Closed by halbmy** 2017-12-14 07:12 UTC

**Comment by florian-wagner** [comment] 2017-12-14 19:59
@halbmy That's why I wrote *with minor modifications*. I didn't mean to say that the except same script works for other DataContainers or that one should use the `pg.DataContainer` for ERT, I just wanted to point out for future reference that other DataContainers (including the base one) can be filled in a similar manner. Wrangling with DataContainers is not very prominent in the documentation.

**Comment by Coastal0** [comment] 2018-03-05 06:13
For a bit of fun, I tried to model this comprehensive dataset example with a slightly modified BERT 
 forward modelling/inversion  tutorial.

```
data = ert.simulate(mesh, res=rhomap, scheme=scheme, noiseLevel=2, noiseAbs=1e-6)
Traceback (most recent call last):

  File "<ipython-input-14-d8d942a0e468>", line 1, in <module>
    data = ert.simulate(mesh, res=rhomap, scheme=scheme, noiseLevel=2, noiseAbs=1e-6)

  File "F:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\pybert\manager\ertmanager.py", line 527, in simulate
    resp = fop.response(res)

RuntimeError: C:/msys64/home/Guenther.T/py36/gimli/gimli/src/bert/datamap.cpp: 219		GIMLI::RVector GIMLI::DataMap::data(const GIMLI::DataContainerERT&, bool, bool) 
 a = -1 b = -1 m = -1 n = -1
 0 0 0 0 U = 0
```
[pyGimli-pyBert_SimpleERI_Modelling_example_comprehensive.py.txt](https://github.com/gimli-org/gimli/files/1779635/pyGimli-pyBert_SimpleERI_Modelling_example_comprehensive.py.txt)

Turns out there was an extra number at the bottom, which I suppose caused the issue.
![image](https://user-images.githubusercontent.com/25240257/36959859-43ade4fa-207f-11e8-8cb4-5812b436f367.png)

![image](https://user-images.githubusercontent.com/25240257/36959847-373dc834-207f-11e8-9e9c-521f4409792e.png)

The `pg.show(data)` is quite interesting!
![figure_1-2](https://user-images.githubusercontent.com/25240257/36959714-77634e9e-207e-11e8-9c54-d45859430af3.png)

It's just working away at the inversion now, but I thought you might be interested to see :)

**Comment by carsten-forty2** [comment] 2018-03-05 18:36
Thanks for reporting, unfortunately I cannot reproduce these exception.

The '0' at the bottom is supposed to be there, it just means there follows zero topography point.

Running your script gives me:

```
Comprehensive data set: 44850 configurations.
*** Deprecated please use 'geometricFactors' /home/carsten/src/gimli/gimli/src/bert/bertMisc.h: 61
relativeError set to a value > 0.5 .. assuming this is a percentage Error level dividing them by 100
Data error estimate (min:max)  0.020000075045587165 : 0.022216669226031556
Simulated rhoa <class 'pygimli.core._pygimli_.RVector'> 44850 [74.57513548149423,...,70.62553813953956] 15041.1992639056
Filtered rhoa <class 'pygimli.core._pygimli_.RVector'> 44850 [74.57513548149423,...,70.62553813953956] 15041.1992639056

```

The data view seems okay to me for this unusual data set.
Note, the data set contains ambiguous measurement schemes (like Wenner vs. Schlumberger)
so its hard to find the best view option automatic.

Cheers,
Carsten

**Comment by halbmy** [comment] 2018-03-06 14:03
When seeing different behaviour, I just saw that pybert comes from the WinPython path, which is really unusual as we do not (unlike for pygimli) provide wheels for pybert. I recommend checking out (and updating) the code with git and use this directory through PYTHONPATH (and getting rid of the site-package variant that might be outdated easily). Otherwise you will have to do `python setup.py install` everytime you pull the code.

About the show output: A pseudosection is a coloured representation of measurements (that are ordered in a way which makes it easy to read) but no section whatsoever. If several array types are present (in your case pole-pole, Wenner and dipole-dipole) they are plotted beneath each other. Everything is ok with it and there is no change expected to it.

**Comment by Coastal0** [comment] 2018-03-07 01:16
Thanks Thomas. I did resort to a hack-job method to get it working on my PC - mostly due to an utter lack of experience with python/compiling/etc. 

I've learnt a little more recently, and will give the installation another shot with the latest version.
