### ISSUE TITLE
Set measurements in crosshole tomography

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/gimli#206] opened 2019-11-08 11:17 UTC
### Problem description
Loaded in my own S/G Geometry for a crosshole tomography 
Forward simulation works fairly well. 

Trying to set picked times in crosshole tomography

### Your environment

**Operating system**: Win 7
**Python version**: 3.6
**pyGIMLi version**:  0.11
**Way of installation**: Conda Wheel

### Steps to reproduce

Tell us how to reproduce this issue. Ideally, you could paste the code that produces the error:

```python

# Most stuff taken from example

rays=measurements[['s','g']].values

# Empty container
scheme = pg.DataContainer()

for sen in sensorarray:
    scheme.createSensor(sen)
    
scheme.resize(len(rays))
scheme.add("s", rays[:, 0])
scheme.add("g", rays[:, 1])
scheme.add("valid", np.ones(len(rays)))
scheme.registerSensorIndex("s")
scheme.registerSensorIndex("g")

tt = Refraction()
mesh_fwd.createSecondaryNodes(5)
data = tt.simulate(mesh=mesh_fwd, scheme=scheme, slowness=1. / model,
                   noiseLevel=0.001, noiseAbs=1e-5)

########### CRUCIAL PART:
data.set('t',list(dt['t'].values)) # dt contains basically the sgt file positions and picks like s g t as pandas df



ttinv = Refraction()
ttinv.setData(data)
ttinv.setMesh(mesh, secNodes=5)
invmodel = ttinv.invert(lam=1100, vtop=2000, vbottom=2000, zWeight=1.0,maxIter=1,verbose=True)

ttinv.showResult()
...
```

### Expected behavior

Inversion running with new t values

### Actual behavior

Throws an error

```
C:/msys64/home/Guenther.T/src/gimli/gimli36/src/inversion.h: 638		double GIMLI::Inversion<ModelValType>::getPhiD(const Vec&) const [with ModelValType = double; GIMLI::Inversion<ModelValType>::Vec = GIMLI::Vector<double>]  getPhiD == inf
```

> If possible, please add one or more labels to your issue, e.g. if you expect that your issue is rather a question than a problem with the code, please add the label "question".

**Comment by halbmy** [comment] 2019-11-08 11:23
I guess the error occurs in the `ttinv.invert()` step? So we can focus on that part. Can you attach the data file (`data.save(filename, 's g t')`) and the mesh (or code for generating it), so that we can try to reproduce it? Maybe it has already been solved in a more recent version.

**Comment by GGDRriedel** [comment] 2019-11-08 12:03
Indeed!
[crosshole.py.txt](https://github.com/gimli-org/gimli/files/3824473/crosshole.py.txt)
[datafile.#dt.txt](https://github.com/gimli-org/gimli/files/3824474/datafile.dt.txt)
[dtreader.py.txt](https://github.com/gimli-org/gimli/files/3824475/dtreader.py.txt)
[thefile.sgt.txt](https://github.com/gimli-org/gimli/files/3824476/thefile.sgt.txt)


I am generating the data from the #dt file, the .sgt is the one generated by dat.save.


Code is a bit messy since I am iteratively working from your example

**Comment by halbmy** [comment] 2019-11-08 12:18
I cannot read the code due to missing dependencies (dtreader), and it is indeed too messy.
Can you please just attach the mesh (`mesh.save() or the x and y vectors) so that we can just use the last 5 lines of the code and not the mess part at the beginning.

**Comment by GGDRriedel** [comment] 2019-11-08 12:49
dtreader is in the files but nevertheless here is the mesh 
[themesh.bms.txt](https://github.com/gimli-org/gimli/files/3824541/themesh.bms.txt)

**Comment by GGDRriedel** [comment] 2019-11-08 12:51
I noticed that in my setup the scheme has 804 data points while the data coming out of the simulation has 777

**Comment by halbmy** [comment] 2019-11-08 12:52
can you add a screenshot of how the synthetic model looks like?

**Comment by halbmy** [comment] 2019-11-08 13:06
No idea whether there are some invalid data reducing the number of data. Anyway, the following script
```Python
import matplotlib as mpl
import pygimli as pg
from pygimli.physics.traveltime import TravelTimeManager as Refraction  # pg 1.1
# from pygimli.physics.traveltime import Refraction # pg1.0
mpl.rcParams['image.cmap'] = 'inferno_r'

data = pg.DataContainer('thefile.sgt', "s g")
mesh = pg.Mesh('themesh.bms')

ttinv = Refraction()
ttinv.setData(data)
ttinv.setMesh(mesh, secNodes=5)
invmodel = ttinv.invert(lam=1100, vtop=2000, vbottom=2000,
                        zWeight=1.0, maxIter=1, verbose=True)

ax, _ = ttinv.showResult()
```
works (using Python 3.7 from Anaconda on Windows) using pyGIMLi 1.1:
![image](https://user-images.githubusercontent.com/7136401/68478161-8ec1b780-022f-11ea-9f36-a69c0b4b3b8f.png)
but not in pyGIMLi 1.0.12.1 (leading to the mentioned PhiD error) I'll check that in detail.

**Comment by GGDRriedel** [comment] 2019-11-08 13:20
![mesh_sensors](https://user-images.githubusercontent.com/48824691/68479507-c8e08880-0232-11ea-9980-c28b2b8e92e6.png)
Mesh and sensors. 

It's probably fixed in a later version since most errors I get seem to be of numerical nature.

I'll try to update to the branch and come back with info.

**Comment by florian-wagner** [comment] 2019-11-08 13:57
@GGDRriedel Release candidates of pygimli 1.1 are available in the test channel: https://anaconda.org/gimli/pygimli/files?version=1.1.0rc5

`conda install -c gimli/label/test -c conda-forge pygimli=1.1.0rc5`

**Comment by halbmy** [comment] 2019-11-08 22:04
Unlike in the crosshole traveltime example
https://www.pygimli.org/_examples_auto/seismics/plot_3_crosshole_tomography.html
your sensors are no nodes in the mesh. While in pyGIMLi 1.1 this seems to be accounted for by choosing the nearest node, in version 1.0 this seems to lead to inaccurate Jacobian matrix. We will not fix this for v1.0 anymore.

Anyway, I guess node-free meshes will lead to inaccuracies also in v1.1. Therefore we recommend (particularly for real-world cases) creating a triangular mesh with all sensor positions in a box instead of a rectangular mesh. This works for both v1.0 and v1.1. 

A reasonable synthetic model should have some structure (otherwise an infinite regularization parameter will lead to a constant model that fits the data) and also some Gaussian noise (with its std used as error) so that the regularization parameter can be chosen accordingly. I see nothing more to do here and close the issue.

**Closed by halbmy** 2019-11-08 22:04 UTC

**Comment by GGDRriedel** [comment] 2019-11-11 15:06
What do you mean by "in a box" ?

**Comment by halbmy** [comment] 2019-11-11 16:21
A box is a rectangle bounding the domain like in the crosshole example https://www.pygimli.org/_examples_auto/seismics/plot_3_crosshole_tomography.html
where all sensors are added as nodes. Please have a look at that.
