### ISSUE TITLE
What's is the best way to define error?

### ISSUE THREAD

**Issue by makeabhishek** [gimli-org/gimli#608] opened 2023-10-26 23:03 UTC
Hi,
I have  obtained traveltime picks from field data, which would obviously have some error. I'm not sure about the subsurface region so don't know exactly the error range in picking the traveltime. What would be the best way to assign error in the data while performing traveltime inversion. 

I'm aware that we can define absolute error in the manager. But what should be the appropriate error value? Is there a approach to do some kind of study to analyse the final inverted model based on the error, which can give confidence to the inverted results? 

I tried to assign absolute error values in the manager and performed the inversion. `Chi^2` value reduces below 1 but the inverted results isn't as expected.  

`InvVel = mgr.invert(mesh=mesh, lam=50, useGradient=0, secNodes=5, absoluteError=10e-6)`

**Comment by halbmy** [comment] 2023-11-01 11:55
Errors in traveltime tomography are manifold: sampling frequency, picking errors, 3D conditions, ... I am not aware of any "unique" solution for estimating the error. Typically you have some idea on how well you are able to fit the data, often absolute errors like 1ms are used for shallow refraction, or a few ms for large-scale problems. I would suggest adding a small relative error (0.1-1%) to account for offset-depending errors. 10µs seems to be extremely low, even if you do ultrasonic.

**Comment by halbmy** [comment] 2023-11-12 20:47
Any comments to this? We cannot proceed with the issue without further knowlege.

**Comment by makeabhishek** [comment] 2023-11-12 23:14
Currently looking and trying to see how error changes the accuracy. 
Wondering when to choose absolute error and relative error, and relative error is restive to what?

**Comment by halbmy** [comment] 2023-11-13 06:34
The relative error is a portion of the data, i.e. the traveltimes. In traveltime tomography, typically an absolute error in the range of a few ms dominates, but a relative error can account for larger errors in long offsets, e.g. caused by 3D effects.

**Comment by makeabhishek** [comment] 2023-11-15 00:06
I'm wondering how can I save the inverted results in a loop. I want to run a model for different error values and then plot the results 

```
for i in range(10,200,10):
    pg.info("Traveltime Inversion")
    velInv = mgr.invert(data, mesh=mesh, lam=50, useGradient=0, zWeight=1.0, secNodes=5, relativeError=i)
    mgr.inv.echoStatus()
    phiModel.append(mgr.inv.phiModel())
    phiData.append(mgr.inv.phiData())
    mgr.inv.chi2History

mgr.showResult(cMap="Spectral_r")
```
Howw can I append the inverted model to plot the results for a particular index?

**Comment by halbmy** [comment] 2023-11-15 06:26
Note that a relative error of 10 (=1000%) does not make sense.

You could collect the models in a list like you do for `phiModel`:
```
models = []
for ...
    models.append(velInv)  # or more rigorously mgr.paraModel

mgr.showResult(models[i], ...)
```

You could also store them in the model (e.g. to show them in ParaView as times)
```
pd = mgr.paraDomain
for i ...
    ...
    pd[f"model{i}"] = velInv
```

**Comment by halbmy** [comment] 2023-11-15 06:28
Note that a relative error is very uncommon, better vary the absolute error.

Note however, that this will probably not bring you forward as a constant regularization parameter does not make sense for different errors using the same data because you could also just change `lam`.

**Comment by makeabhishek** [comment] 2023-11-15 11:05
So in this case, thee will be different lambda for different error. Am I correct? Is there a relationship between error and lambda? Best RegardsAbhishekOn 14 Nov 2023, at 11:28 PM, Thomas Günther ***@***.***> wrote:﻿
Note that a relative error is very uncommon, better vary the absolute error.
Note however, that this will probably not bring you forward as a constant regularization parameter does not make sense for different errors using the same data because you could also just change lam.

**Comment by halbmy** [comment] 2023-11-15 11:12
The lambda value should alway be adapted so that the data are fitted within noise (chi-square=1)

**Comment by makeabhishek** [comment] 2023-11-15 17:09
I didnt understand the comment above  

```
You could also store them in the model (e.g. to show them in ParaView as times)

pd = mgr.paraDomain
for i ...
    ...
    pd[f"model{i}"] = velInv
```
Can we visualize pygimli results in paraview?

**Comment by halbmy** [comment] 2023-11-15 20:03
The model vectors are stored inside the mesh as model0, model1, .... Did you try to adapt that? 

You can export the result then by `pd.exportVTK("bla.vtk")`

As the last questions left the original subject (error estimation), I am closing the issue.

**Closed by halbmy** 2023-11-15 20:03 UTC
